### ISSUE TITLE
ftd.markup to accept `{$variable}`

### ISSUE THREAD

**Issue by amitu** [FifthTry/ftd#53] opened 2022-01-07 05:48 UTC
We can currently do: 

```ftd

-- ftd.markup:

Hello, {name}.

-- ftd.text name: $name
```

We should be able to also do:

```ftd

-- ftd.markup:

Hello, {$name}.
```

**Comment by sharmashobhit** [comment] 2022-02-24 07:32
Duplicate of #123

**Closed by sharmashobhit** 2022-02-24 07:32 UTC
Labels: feature: markup
